[versions]
compose-compiler = "1.5.4"

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.7.0"
androidx-browser = "androidx.browser:browser:1.7.0"
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
