[versions]
compose-compiler = "1.5.13"

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-browser = "androidx.browser:browser:1.9.0"
androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
