[versions]
compose-compiler = "1.5.13"

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.7.1"
androidx-browser = "androidx.browser:browser:1.8.0"
androidx-core-ktx = "androidx.core:core-ktx:1.13.1"
