[versions]
android-gradle = "8.0.2"
dokkatoo = "1.6.0"
kotest = "5.6.2"
kotlin = "1.8.21"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

[plugins]
kotlinx-bcv = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.1"
android-gradle-library = { id = "com.android.library", version.ref = "android-gradle" }
dokkatoo-html = { id = "dev.adamko.dokkatoo-html", version.ref = "dokkatoo" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
