[versions]
android-gradle = "8.0.2"
dokkatoo = "1.5.0"
kotlin = "1.8.21"

[plugins]
kotlinx-bcv = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.1"
android-gradle-library = { id = "com.android.library", version.ref = "android-gradle" }
dokkatoo-html = { id = "dev.adamko.dokkatoo-html", version.ref = "dokkatoo" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
