/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.edricchan03.androidx.ktx

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
