# This workflow will deploy Dokka documentation to GitHub Pages whenever
# content is pushed to the main branch, or it can be triggered manually in
# the Actions tab

name: Docs

on:
  push:
    branches:
      - main # Only allow pushes from the main branch
  # Allow for manual deployments
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy-docs:
    name: Build and deploy docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17 # AGP requires Java 17 since 8.0+
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          gradle-home-cache-strict-match: true

      - name: Build docs
#        run: ./gradlew dokkatooGeneratePublicationHtml --stacktrace
        run: ./gradlew dokkaHtmlMultiModule --stacktrace

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload Dokka folder
          path: './build/dokka/htmlMultiModule'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
