# This workflow will deploy Dokka documentation to GitHub Pages whenever
# content is pushed to the main branch, or it can be triggered manually in
# the Actions tab

name: Docs

on:
  push:
    branches:
      - main # Only allow pushes from the main branch
  # Allow for manual deployments
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy-docs:
    name: Build and deploy docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # AGP requires Java 17 since 8.0+
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build docs
        run: ./gradlew dokkaGeneratePublicationHtml --stacktrace

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload Dokka folder
          path: './build/dokka/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
